a=[3,7,2,6,9,1]
a.sort()
print(a)
a=[3,7,2,6,9,1]
a.sort(reverse=true)
print(a)
a=["bee","moth","wasp","ant"]
a.sort()
print(a)
a=["bee","wasp","butterfly"]
a.sort(key=len)
print(a)
a=["bee","wasp","butterfly"]
a.sort(key=len,reverse=true)
print(a)
